version: "3"

services:
    tourfirma-nginx:
        container_name: tourfirma-nginx
        build: ./docker/nginx
        volumes:
            - .:/var/www/html
        ports:
            - 8005:80

    tourfirma-php:
        container_name: tourfirma-php
        build: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/html
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    tourfirma-mysql:
        container_name: tourfirma-mysql
        build: docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tourfirma_db
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - 3311:3306
